In [1]:
%matplotlib inline
import os

import matplotlib

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# to make this notebook's output stable across runs
np.random.seed(42)

plt.rcParams['axes.labelsize'] = 14
plt.rcParams['xtick.labelsize'] = 12
plt.rcParams['ytick.labelsize'] = 12

# Where to save the figures
PROJECT_ROOT_DIR = "."
CHAPTER_ID = "end_to_end_project"
IMAGES_PATH = os.path.join(PROJECT_ROOT_DIR, "images", CHAPTER_ID)

def save_fig(fig_id, tight_layout=True, fig_extension="png", resolution=300):
    path = os.path.join(IMAGES_PATH, fig_id + "." + fig_extension)
    print("Saving figure", fig_id)
    if tight_layout:
        plt.tight_layout()
    plt.savefig(path, format=fig_extension, dpi=resolution)

# Ignore useless warnings (see SciPy issue #5998)
import warnings
warnings.filterwarnings(action="ignore", message="^internal gelsd")


In [2]:
# 创建并运行一个图谱
import tensorflow as tf

In [3]:
x = tf.Variable(3, name="x")
y = tf.Variable(4, name='y')

f = x*x*y +y +2

In [4]:
# 第一种运行方式
sess = tf.Session()
sess.run(x.initializer)
sess.run(y.initializer)
result = sess.run(f)

print(result)
sess.close()

42


In [5]:
# 第二种运行方式
with tf.Session() as sess:
    x.initializer.run()
    y.initializer.run()
    result = f.eval()

print(result)

42


In [6]:
# 第三种运行方式
init = tf.global_variables_initializer()
sess = tf.InteractiveSession()
init.run()
result = f.eval()
print(result)
sess.close()

42


In [7]:
# TensorFlow 程序通常分为两部分：第一部分构建计算图谱（这称为构造阶段），第二部分运 行它（这是执行阶段）

In [8]:
# 管理图谱
# 创建的任意节点都会自动添加到默认图形中
x1  = tf.Variable(1)

x1.graph is tf.get_default_graph()

True

In [9]:
# 当需要管理多个图形的时候 就需要管理多个独立图形
graph = tf.Graph()

with graph.as_default():
    x2 = tf.Variable(2)
x2.graph is graph

True

In [10]:
x2.graph is tf.get_default_graph()

False

In [11]:
# 节点值的生命周期
w = tf.constant(3)
x = w + 2
y = x + 5
z = x * 3

with tf.Session() as sess:
    print(y.eval())
    print(z.eval())

10
15


In [12]:
# Linear Regression with TensorFlow
from sklearn.datasets import fetch_california_housing

housing = fetch_california_housing()
m, n = housing.data.shape
#np.c_按colunm来组合array
housing_data_plus_bias = np.c_[np.ones((m, 1)), housing.data]

In [13]:
housing_data_plus_bias, housing_data_plus_bias.shape

(array([[   1.        ,    8.3252    ,   41.        , ...,    2.55555556,
           37.88      , -122.23      ],
        [   1.        ,    8.3014    ,   21.        , ...,    2.10984183,
           37.86      , -122.22      ],
        [   1.        ,    7.2574    ,   52.        , ...,    2.80225989,
           37.85      , -122.24      ],
        ...,
        [   1.        ,    1.7       ,   17.        , ...,    2.3256351 ,
           39.43      , -121.22      ],
        [   1.        ,    1.8672    ,   18.        , ...,    2.12320917,
           39.43      , -121.32      ],
        [   1.        ,    2.3886    ,   16.        , ...,    2.61698113,
           39.37      , -121.24      ]]), (20640, 9))

In [14]:
housing.target, len(housing.target)

(array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894]), 20640)

In [15]:
housing.target.reshape(-1, 1)

array([[4.526],
       [3.585],
       [3.521],
       ...,
       [0.923],
       [0.847],
       [0.894]])

In [16]:
X = tf.constant(housing_data_plus_bias, dtype=tf.float32, name="X")
y = tf.constant(housing.target.reshape(-1, 1), dtype=tf.float32, name="y")
XT = tf.transpose(X)
theta = tf.matmul(tf.matmul(tf.matrix_inverse(tf.matmul(XT, X)), XT), y)

with tf.Session() as sess:
    theta_value = theta.eval()

In [17]:
theta_value

array([[-3.7185181e+01],
       [ 4.3633747e-01],
       [ 9.3952334e-03],
       [-1.0711310e-01],
       [ 6.4479220e-01],
       [-4.0338000e-06],
       [-3.7813708e-03],
       [-4.2348403e-01],
       [-4.3721911e-01]], dtype=float32)

In [18]:
housing.data[0]

array([   8.3252    ,   41.        ,    6.98412698,    1.02380952,
        322.        ,    2.55555556,   37.88      , -122.23      ])