## Basic introduction to TensorFlow's Eager API

简单介绍一下 TensorFlow 的 Eager API：

- Author: Aymeric Damien
- Project: https://github.com/aymericdamien/TensorFlow-Examples/

### What is TensorFlow's Eager API ?

>`Eager`操作是个命令式的逐个运行的接口，在这个接口中，操作从 Python 调用时就立即执行
这让学习TensorFlow变得容易，并且使研究和开发变得直观，无论是否开启`eager execution`，绝大多数 TensorFlow API 都保持不变
因此，构造 TensorFlow 图的完全相同的代码(例如使用层 API)可以通过使用 `eager execution` 来强制执行
相反，大多数使用启用`Eager`编写的模型都可以转换为可以进一步优化和/或提取的图，以便在不更改代码的情况下在生产中进行部署 - Rajat Monga

更多：[https://ai.googleblog.com/2017/10/eager-execution-imperative-define-by.html](https://ai.googleblog.com/2017/10/eager-execution-imperative-define-by.html)

In [1]:
import numpy as np
import tensorflow as tf

In [2]:
# Set Eager API
print("Setting Eager mode...")
tf.enable_eager_execution()
tfe = tf.contrib.eager

Setting Eager mode...


In [3]:
tfe

<module 'tensorflow.contrib.eager.python.tfe' from '/Users/a2017148/.local/share/virtualenvs/pylab--mHOjq_e/lib/python3.6/site-packages/tensorflow/contrib/eager/python/tfe.py'>

In [4]:
# Define constant tensors
print("Define constant tensors")
a = tf.constant(2)
print("a = %i" % a)
b = tf.constant(3)
print("b = %i" % b)

Define constant tensors
a = 2
b = 3


In [5]:
# Run the operation without the need for tf.Session
print("Running operations, without tf.Session")
c = a + b
print("a + b = %i" % c)
d = a * b
print("a * b = %i" % d)

Running operations, without tf.Session
a + b = 5
a * b = 6


In [6]:
# 和 Numpy 完美兼容
# Full compatibility with Numpy
print("Mixing operations with Tensors and Numpy Arrays")

# Define constant tensors
a = tf.constant([[2., 1.],
                 [1., 0.]], dtype=tf.float32)
print("Tensor:\n a = %s" % a)
b = np.array([[3., 0.],
              [5., 1.]], dtype=np.float32)
print("NumpyArray:\n b = %s" % b)

Mixing operations with Tensors and Numpy Arrays
Tensor:
 a = tf.Tensor(
[[2. 1.]
 [1. 0.]], shape=(2, 2), dtype=float32)
NumpyArray:
 b = [[3. 0.]
 [5. 1.]]


In [7]:
# Run the operation without the need for tf.Session
print("Running operations, without tf.Session")

c = a + b
print("a + b = %s" % c)

d = tf.matmul(a, b)
print("a * b = %s" % d)

Running operations, without tf.Session
a + b = tf.Tensor(
[[5. 1.]
 [6. 1.]], shape=(2, 2), dtype=float32)
a * b = tf.Tensor(
[[11.  1.]
 [ 3.  0.]], shape=(2, 2), dtype=float32)


In [8]:
print("Iterate through Tensor 'a':")
for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        print(a[i][j])

Iterate through Tensor 'a':
tf.Tensor(2.0, shape=(), dtype=float32)
tf.Tensor(1.0, shape=(), dtype=float32)
tf.Tensor(1.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
